//
// Copyright Jason Rice 2015
// Distributed under the Boost Software License, Version 1.0.
// (See accompanying file LICENSE_1_0.txt or copy at
// http://www.boost.org/LICENSE_1_0.txt)
//
#ifndef NBDL_MEMBER_IDS

#include "VFUNC.hpp"

/*
 * automatically generates ids for members of entity
 * based on order
 */
#define NBDL_MEMBER_IDS(NAME, ...) NBDL_MEMBER_IDS_N(NAME, __NARG__(__VA_ARGS__), __VA_ARGS__)
#define NBDL_MEMBER_IDS_N(...) VFUNC(NBDL_MEMBER_IDS, __VA_ARGS__)

//61 is probably too many as compilers limit macro arg count to 64
#define NBDL_MEMBER_IDS63(NAME, SIZE, MNAME, ...) NBDL_MEMBER_ID(&NAME::MNAME, SIZE - 61) \
 NBDL_MEMBER_IDS62(NAME, SIZE, __VA_ARGS__)
#define NBDL_MEMBER_IDS62(NAME, SIZE, MNAME, ...) NBDL_MEMBER_ID(&NAME::MNAME, SIZE - 60) \
 NBDL_MEMBER_IDS61(NAME, SIZE, __VA_ARGS__)
#define NBDL_MEMBER_IDS61(NAME, SIZE, MNAME, ...) NBDL_MEMBER_ID(&NAME::MNAME, SIZE - 59) \
 NBDL_MEMBER_IDS60(NAME, SIZE, __VA_ARGS__)
#define NBDL_MEMBER_IDS60(NAME, SIZE, MNAME, ...) NBDL_MEMBER_ID(&NAME::MNAME, SIZE - 58) \
 NBDL_MEMBER_IDS59(NAME, SIZE, __VA_ARGS__)
#define NBDL_MEMBER_IDS59(NAME, SIZE, MNAME, ...) NBDL_MEMBER_ID(&NAME::MNAME, SIZE - 57) \
 NBDL_MEMBER_IDS58(NAME, SIZE, __VA_ARGS__)
#define NBDL_MEMBER_IDS58(NAME, SIZE, MNAME, ...) NBDL_MEMBER_ID(&NAME::MNAME, SIZE - 56) \
 NBDL_MEMBER_IDS57(NAME, SIZE, __VA_ARGS__)
#define NBDL_MEMBER_IDS57(NAME, SIZE, MNAME, ...) NBDL_MEMBER_ID(&NAME::MNAME, SIZE - 55) \
 NBDL_MEMBER_IDS56(NAME, SIZE, __VA_ARGS__)
#define NBDL_MEMBER_IDS56(NAME, SIZE, MNAME, ...) NBDL_MEMBER_ID(&NAME::MNAME, SIZE - 54) \
 NBDL_MEMBER_IDS55(NAME, SIZE, __VA_ARGS__)
#define NBDL_MEMBER_IDS55(NAME, SIZE, MNAME, ...) NBDL_MEMBER_ID(&NAME::MNAME, SIZE - 53) \
 NBDL_MEMBER_IDS54(NAME, SIZE, __VA_ARGS__)
#define NBDL_MEMBER_IDS54(NAME, SIZE, MNAME, ...) NBDL_MEMBER_ID(&NAME::MNAME, SIZE - 52) \
 NBDL_MEMBER_IDS53(NAME, SIZE, __VA_ARGS__)
#define NBDL_MEMBER_IDS53(NAME, SIZE, MNAME, ...) NBDL_MEMBER_ID(&NAME::MNAME, SIZE - 51) \
 NBDL_MEMBER_IDS52(NAME, SIZE, __VA_ARGS__)
#define NBDL_MEMBER_IDS52(NAME, SIZE, MNAME, ...) NBDL_MEMBER_ID(&NAME::MNAME, SIZE - 50) \
 NBDL_MEMBER_IDS51(NAME, SIZE, __VA_ARGS__)
#define NBDL_MEMBER_IDS51(NAME, SIZE, MNAME, ...) NBDL_MEMBER_ID(&NAME::MNAME, SIZE - 49) \
 NBDL_MEMBER_IDS50(NAME, SIZE, __VA_ARGS__)
#define NBDL_MEMBER_IDS50(NAME, SIZE, MNAME, ...) NBDL_MEMBER_ID(&NAME::MNAME, SIZE - 48) \
 NBDL_MEMBER_IDS49(NAME, SIZE, __VA_ARGS__)
#define NBDL_MEMBER_IDS49(NAME, SIZE, MNAME, ...) NBDL_MEMBER_ID(&NAME::MNAME, SIZE - 47) \
 NBDL_MEMBER_IDS48(NAME, SIZE, __VA_ARGS__)
#define NBDL_MEMBER_IDS48(NAME, SIZE, MNAME, ...) NBDL_MEMBER_ID(&NAME::MNAME, SIZE - 46) \
 NBDL_MEMBER_IDS47(NAME, SIZE, __VA_ARGS__)
#define NBDL_MEMBER_IDS47(NAME, SIZE, MNAME, ...) NBDL_MEMBER_ID(&NAME::MNAME, SIZE - 45) \
 NBDL_MEMBER_IDS46(NAME, SIZE, __VA_ARGS__)
#define NBDL_MEMBER_IDS46(NAME, SIZE, MNAME, ...) NBDL_MEMBER_ID(&NAME::MNAME, SIZE - 44) \
 NBDL_MEMBER_IDS45(NAME, SIZE, __VA_ARGS__)
#define NBDL_MEMBER_IDS45(NAME, SIZE, MNAME, ...) NBDL_MEMBER_ID(&NAME::MNAME, SIZE - 43) \
 NBDL_MEMBER_IDS44(NAME, SIZE, __VA_ARGS__)
#define NBDL_MEMBER_IDS44(NAME, SIZE, MNAME, ...) NBDL_MEMBER_ID(&NAME::MNAME, SIZE - 42) \
 NBDL_MEMBER_IDS43(NAME, SIZE, __VA_ARGS__)
#define NBDL_MEMBER_IDS43(NAME, SIZE, MNAME, ...) NBDL_MEMBER_ID(&NAME::MNAME, SIZE - 41) \
 NBDL_MEMBER_IDS42(NAME, SIZE, __VA_ARGS__)
#define NBDL_MEMBER_IDS42(NAME, SIZE, MNAME, ...) NBDL_MEMBER_ID(&NAME::MNAME, SIZE - 40) \
 NBDL_MEMBER_IDS41(NAME, SIZE, __VA_ARGS__)
#define NBDL_MEMBER_IDS41(NAME, SIZE, MNAME, ...) NBDL_MEMBER_ID(&NAME::MNAME, SIZE - 39) \
 NBDL_MEMBER_IDS40(NAME, SIZE, __VA_ARGS__)
#define NBDL_MEMBER_IDS40(NAME, SIZE, MNAME, ...) NBDL_MEMBER_ID(&NAME::MNAME, SIZE - 38) \
 NBDL_MEMBER_IDS39(NAME, SIZE, __VA_ARGS__)
#define NBDL_MEMBER_IDS39(NAME, SIZE, MNAME, ...) NBDL_MEMBER_ID(&NAME::MNAME, SIZE - 37) \
 NBDL_MEMBER_IDS38(NAME, SIZE, __VA_ARGS__)
#define NBDL_MEMBER_IDS38(NAME, SIZE, MNAME, ...) NBDL_MEMBER_ID(&NAME::MNAME, SIZE - 36) \
 NBDL_MEMBER_IDS37(NAME, SIZE, __VA_ARGS__)
#define NBDL_MEMBER_IDS37(NAME, SIZE, MNAME, ...) NBDL_MEMBER_ID(&NAME::MNAME, SIZE - 35) \
 NBDL_MEMBER_IDS36(NAME, SIZE, __VA_ARGS__)
#define NBDL_MEMBER_IDS36(NAME, SIZE, MNAME, ...) NBDL_MEMBER_ID(&NAME::MNAME, SIZE - 34) \
 NBDL_MEMBER_IDS35(NAME, SIZE, __VA_ARGS__)
#define NBDL_MEMBER_IDS35(NAME, SIZE, MNAME, ...) NBDL_MEMBER_ID(&NAME::MNAME, SIZE - 33) \
 NBDL_MEMBER_IDS34(NAME, SIZE, __VA_ARGS__)
#define NBDL_MEMBER_IDS34(NAME, SIZE, MNAME, ...) NBDL_MEMBER_ID(&NAME::MNAME, SIZE - 32) \
 NBDL_MEMBER_IDS33(NAME, SIZE, __VA_ARGS__)
#define NBDL_MEMBER_IDS33(NAME, SIZE, MNAME, ...) NBDL_MEMBER_ID(&NAME::MNAME, SIZE - 31) \
 NBDL_MEMBER_IDS32(NAME, SIZE, __VA_ARGS__)
#define NBDL_MEMBER_IDS32(NAME, SIZE, MNAME, ...) NBDL_MEMBER_ID(&NAME::MNAME, SIZE - 30) \
 NBDL_MEMBER_IDS31(NAME, SIZE, __VA_ARGS__)
#define NBDL_MEMBER_IDS31(NAME, SIZE, MNAME, ...) NBDL_MEMBER_ID(&NAME::MNAME, SIZE - 29) \
 NBDL_MEMBER_IDS30(NAME, SIZE, __VA_ARGS__)
#define NBDL_MEMBER_IDS30(NAME, SIZE, MNAME, ...) NBDL_MEMBER_ID(&NAME::MNAME, SIZE - 28) \
 NBDL_MEMBER_IDS29(NAME, SIZE, __VA_ARGS__)
#define NBDL_MEMBER_IDS29(NAME, SIZE, MNAME, ...) NBDL_MEMBER_ID(&NAME::MNAME, SIZE - 27) \
 NBDL_MEMBER_IDS28(NAME, SIZE, __VA_ARGS__)
#define NBDL_MEMBER_IDS28(NAME, SIZE, MNAME, ...) NBDL_MEMBER_ID(&NAME::MNAME, SIZE - 26) \
 NBDL_MEMBER_IDS27(NAME, SIZE, __VA_ARGS__)
#define NBDL_MEMBER_IDS27(NAME, SIZE, MNAME, ...) NBDL_MEMBER_ID(&NAME::MNAME, SIZE - 25) \
 NBDL_MEMBER_IDS26(NAME, SIZE, __VA_ARGS__)
#define NBDL_MEMBER_IDS26(NAME, SIZE, MNAME, ...) NBDL_MEMBER_ID(&NAME::MNAME, SIZE - 24) \
 NBDL_MEMBER_IDS25(NAME, SIZE, __VA_ARGS__)
#define NBDL_MEMBER_IDS25(NAME, SIZE, MNAME, ...) NBDL_MEMBER_ID(&NAME::MNAME, SIZE - 23) \
 NBDL_MEMBER_IDS24(NAME, SIZE, __VA_ARGS__)
#define NBDL_MEMBER_IDS24(NAME, SIZE, MNAME, ...) NBDL_MEMBER_ID(&NAME::MNAME, SIZE - 22) \
 NBDL_MEMBER_IDS23(NAME, SIZE, __VA_ARGS__)
#define NBDL_MEMBER_IDS23(NAME, SIZE, MNAME, ...) NBDL_MEMBER_ID(&NAME::MNAME, SIZE - 21) \
 NBDL_MEMBER_IDS22(NAME, SIZE, __VA_ARGS__)
#define NBDL_MEMBER_IDS22(NAME, SIZE, MNAME, ...) NBDL_MEMBER_ID(&NAME::MNAME, SIZE - 20) \
 NBDL_MEMBER_IDS21(NAME, SIZE, __VA_ARGS__)
#define NBDL_MEMBER_IDS21(NAME, SIZE, MNAME, ...) NBDL_MEMBER_ID(&NAME::MNAME, SIZE - 19) \
 NBDL_MEMBER_IDS20(NAME, SIZE, __VA_ARGS__)
#define NBDL_MEMBER_IDS20(NAME, SIZE, MNAME, ...) NBDL_MEMBER_ID(&NAME::MNAME, SIZE - 18) \
 NBDL_MEMBER_IDS19(NAME, SIZE, __VA_ARGS__)
#define NBDL_MEMBER_IDS19(NAME, SIZE, MNAME, ...) NBDL_MEMBER_ID(&NAME::MNAME, SIZE - 17) \
 NBDL_MEMBER_IDS18(NAME, SIZE, __VA_ARGS__)
#define NBDL_MEMBER_IDS18(NAME, SIZE, MNAME, ...) NBDL_MEMBER_ID(&NAME::MNAME, SIZE - 16) \
 NBDL_MEMBER_IDS17(NAME, SIZE, __VA_ARGS__)
#define NBDL_MEMBER_IDS17(NAME, SIZE, MNAME, ...) NBDL_MEMBER_ID(&NAME::MNAME, SIZE - 15) \
 NBDL_MEMBER_IDS16(NAME, SIZE, __VA_ARGS__)
#define NBDL_MEMBER_IDS16(NAME, SIZE, MNAME, ...) NBDL_MEMBER_ID(&NAME::MNAME, SIZE - 14) \
 NBDL_MEMBER_IDS15(NAME, SIZE, __VA_ARGS__)
#define NBDL_MEMBER_IDS15(NAME, SIZE, MNAME, ...) NBDL_MEMBER_ID(&NAME::MNAME, SIZE - 13) \
 NBDL_MEMBER_IDS14(NAME, SIZE, __VA_ARGS__)
#define NBDL_MEMBER_IDS14(NAME, SIZE, MNAME, ...) NBDL_MEMBER_ID(&NAME::MNAME, SIZE - 12) \
 NBDL_MEMBER_IDS13(NAME, SIZE, __VA_ARGS__)
#define NBDL_MEMBER_IDS13(NAME, SIZE, MNAME, ...) NBDL_MEMBER_ID(&NAME::MNAME, SIZE - 11) \
 NBDL_MEMBER_IDS12(NAME, SIZE, __VA_ARGS__)
#define NBDL_MEMBER_IDS12(NAME, SIZE, MNAME, ...) NBDL_MEMBER_ID(&NAME::MNAME, SIZE - 10) \
 NBDL_MEMBER_IDS11(NAME, SIZE, __VA_ARGS__)
#define NBDL_MEMBER_IDS11(NAME, SIZE, MNAME, ...) NBDL_MEMBER_ID(&NAME::MNAME, SIZE - 9) \
 NBDL_MEMBER_IDS10(NAME, SIZE, __VA_ARGS__)
#define NBDL_MEMBER_IDS10(NAME, SIZE, MNAME, ...) NBDL_MEMBER_ID(&NAME::MNAME, SIZE - 8) \
 NBDL_MEMBER_IDS9(NAME, SIZE, __VA_ARGS__)
#define NBDL_MEMBER_IDS9(NAME, SIZE, MNAME, ...) NBDL_MEMBER_ID(&NAME::MNAME, SIZE - 7) \
 NBDL_MEMBER_IDS8(NAME, SIZE, __VA_ARGS__)
#define NBDL_MEMBER_IDS8(NAME, SIZE, MNAME, ...) NBDL_MEMBER_ID(&NAME::MNAME, SIZE - 6) \
 NBDL_MEMBER_IDS7(NAME, SIZE, __VA_ARGS__)
#define NBDL_MEMBER_IDS7(NAME, SIZE, MNAME, ...) NBDL_MEMBER_ID(&NAME::MNAME, SIZE - 5) \
 NBDL_MEMBER_IDS6(NAME, SIZE, __VA_ARGS__)
#define NBDL_MEMBER_IDS6(NAME, SIZE, MNAME, ...) NBDL_MEMBER_ID(&NAME::MNAME, SIZE - 4) \
 NBDL_MEMBER_IDS5(NAME, SIZE, __VA_ARGS__)
#define NBDL_MEMBER_IDS5(NAME, SIZE, MNAME, ...) NBDL_MEMBER_ID(&NAME::MNAME, SIZE - 3) \
 NBDL_MEMBER_IDS4(NAME, SIZE, __VA_ARGS__)
#define NBDL_MEMBER_IDS4(NAME, SIZE, MNAME, ...) NBDL_MEMBER_ID(&NAME::MNAME, SIZE - 2) \
 NBDL_MEMBER_IDS3(NAME, SIZE, __VA_ARGS__)
#define NBDL_MEMBER_IDS3(NAME, SIZE, MNAME, ...) NBDL_MEMBER_ID(&NAME::MNAME, SIZE - 1)


#endif
