FROM ricejasonf/emscripten
WORKDIR /usr/local/src

# JsonCpp
RUN git clone https://github.com/open-source-parsers/jsoncpp.git \
  && cd jsoncpp && mkdir build && cd build \
  && cmake \
    -DCMAKE_INSTALL_PREFIX=/usr/local \
    -DCMAKE_BUILD_TYPE=Release \
    -DCMAKE_CXX_FLAGS=" -stdlib=libc++" \
    -DCMAKE_EXE_LINKER_FLAGS=" -lc++abi" \
    .. \
  && make install \
  && mkdir /usr/local/include/jsoncpp \
  && cp -r /usr/local/include/json /usr/local/include/jsoncpp/ \
  && rm -rf jsoncpp

# Asio
RUN git clone https://github.com/chriskohlhoff/asio.git \
  && cp asio/asio/include/asio.hpp /usr/local/include \
  && cp -r asio/asio/include/asio /usr/local/include \
  && rm -rf asio

# Boost.Hana (workaround branch)
RUN git clone -b bugfix/constexpr_arrays https://github.com/ricejasonf/hana.git \
  && cp -r hana/include/* /usr/local/include \
  && rm -rf hana

# Boost.CallableTraits
RUN git clone -b master https://github.com/badair/callable_traits.git \
  && cp -r callable_traits/include/* /usr/local/include \
  && rm -rf callable_traits

# Dyno
RUN git clone -b master https://github.com/ldionne/dyno.git \
  && cp -r dyno/include/* /usr/local/include \
  && rm -rf dyno

# Kvasir.Mpl
RUN git clone -b development https://github.com/kvasir-io/mpl.git \
  && cd mpl && git checkout 41c85408d7777b6d476fe70cd6cfcaad8f02a19c && cd .. \
  && cp -r mpl/src/* /usr/local/include \
  && rm -rf mpl

ARG BUILD_TYPE=Debug
ENV BUILD_TYPE ${BUILD_TYPE}

WORKDIR /opt/build
CMD cmake \
  -DCMAKE_BUILD_TYPE=$BUILD_TYPE \
  -DCMAKE_CXX_FLAGS=" -stdlib=libc++ -DASIO_STANDALONE -DASIO_NO_TYPEID" \
  -DCMAKE_EXE_LINKER_FLAGS=" -lc++abi" \
  /opt/src \
  && /bin/bash
