#ifndef NBDL_MEMBERS

#include "VFUNC.hpp"

#define NBDL_MEMBERS(...) VFUNC(NBDL_MEMBERS, __VA_ARGS__)

#define NBDL_MEMBERS63(NAME, MNAME, ...) NBDL_MEMBERS2(NAME, MNAME), \
 NBDL_MEMBERS62(NAME, __VA_ARGS__)
#define NBDL_MEMBERS62(NAME, MNAME, ...) NBDL_MEMBERS2(NAME, MNAME), \
	 NBDL_MEMBERS61(NAME, __VA_ARGS__)
#define NBDL_MEMBERS61(NAME, MNAME, ...) NBDL_MEMBERS2(NAME, MNAME), \
	 NBDL_MEMBERS60(NAME, __VA_ARGS__)
#define NBDL_MEMBERS60(NAME, MNAME, ...) NBDL_MEMBERS2(NAME, MNAME), \
	 NBDL_MEMBERS59(NAME, __VA_ARGS__)
#define NBDL_MEMBERS59(NAME, MNAME, ...) NBDL_MEMBERS2(NAME, MNAME), \
	 NBDL_MEMBERS58(NAME, __VA_ARGS__)
#define NBDL_MEMBERS58(NAME, MNAME, ...) NBDL_MEMBERS2(NAME, MNAME), \
	 NBDL_MEMBERS57(NAME, __VA_ARGS__)
#define NBDL_MEMBERS57(NAME, MNAME, ...) NBDL_MEMBERS2(NAME, MNAME), \
	 NBDL_MEMBERS56(NAME, __VA_ARGS__)
#define NBDL_MEMBERS56(NAME, MNAME, ...) NBDL_MEMBERS2(NAME, MNAME), \
	 NBDL_MEMBERS55(NAME, __VA_ARGS__)
#define NBDL_MEMBERS55(NAME, MNAME, ...) NBDL_MEMBERS2(NAME, MNAME), \
	 NBDL_MEMBERS54(NAME, __VA_ARGS__)
#define NBDL_MEMBERS54(NAME, MNAME, ...) NBDL_MEMBERS2(NAME, MNAME), \
	 NBDL_MEMBERS53(NAME, __VA_ARGS__)
#define NBDL_MEMBERS53(NAME, MNAME, ...) NBDL_MEMBERS2(NAME, MNAME), \
	 NBDL_MEMBERS52(NAME, __VA_ARGS__)
#define NBDL_MEMBERS52(NAME, MNAME, ...) NBDL_MEMBERS2(NAME, MNAME), \
	 NBDL_MEMBERS51(NAME, __VA_ARGS__)
#define NBDL_MEMBERS51(NAME, MNAME, ...) NBDL_MEMBERS2(NAME, MNAME), \
	 NBDL_MEMBERS50(NAME, __VA_ARGS__)
#define NBDL_MEMBERS50(NAME, MNAME, ...) NBDL_MEMBERS2(NAME, MNAME), \
	 NBDL_MEMBERS49(NAME, __VA_ARGS__)
#define NBDL_MEMBERS49(NAME, MNAME, ...) NBDL_MEMBERS2(NAME, MNAME), \
	 NBDL_MEMBERS48(NAME, __VA_ARGS__)
#define NBDL_MEMBERS48(NAME, MNAME, ...) NBDL_MEMBERS2(NAME, MNAME), \
	 NBDL_MEMBERS47(NAME, __VA_ARGS__)
#define NBDL_MEMBERS47(NAME, MNAME, ...) NBDL_MEMBERS2(NAME, MNAME), \
	 NBDL_MEMBERS46(NAME, __VA_ARGS__)
#define NBDL_MEMBERS46(NAME, MNAME, ...) NBDL_MEMBERS2(NAME, MNAME), \
	 NBDL_MEMBERS45(NAME, __VA_ARGS__)
#define NBDL_MEMBERS45(NAME, MNAME, ...) NBDL_MEMBERS2(NAME, MNAME), \
	 NBDL_MEMBERS44(NAME, __VA_ARGS__)
#define NBDL_MEMBERS44(NAME, MNAME, ...) NBDL_MEMBERS2(NAME, MNAME), \
	 NBDL_MEMBERS43(NAME, __VA_ARGS__)
#define NBDL_MEMBERS43(NAME, MNAME, ...) NBDL_MEMBERS2(NAME, MNAME), \
	 NBDL_MEMBERS42(NAME, __VA_ARGS__)
#define NBDL_MEMBERS42(NAME, MNAME, ...) NBDL_MEMBERS2(NAME, MNAME), \
	 NBDL_MEMBERS41(NAME, __VA_ARGS__)
#define NBDL_MEMBERS41(NAME, MNAME, ...) NBDL_MEMBERS2(NAME, MNAME), \
	 NBDL_MEMBERS40(NAME, __VA_ARGS__)
#define NBDL_MEMBERS40(NAME, MNAME, ...) NBDL_MEMBERS2(NAME, MNAME), \
	 NBDL_MEMBERS39(NAME, __VA_ARGS__)
#define NBDL_MEMBERS39(NAME, MNAME, ...) NBDL_MEMBERS2(NAME, MNAME), \
	 NBDL_MEMBERS38(NAME, __VA_ARGS__)
#define NBDL_MEMBERS38(NAME, MNAME, ...) NBDL_MEMBERS2(NAME, MNAME), \
	 NBDL_MEMBERS37(NAME, __VA_ARGS__)
#define NBDL_MEMBERS37(NAME, MNAME, ...) NBDL_MEMBERS2(NAME, MNAME), \
	 NBDL_MEMBERS36(NAME, __VA_ARGS__)
#define NBDL_MEMBERS36(NAME, MNAME, ...) NBDL_MEMBERS2(NAME, MNAME), \
	 NBDL_MEMBERS35(NAME, __VA_ARGS__)
#define NBDL_MEMBERS35(NAME, MNAME, ...) NBDL_MEMBERS2(NAME, MNAME), \
	 NBDL_MEMBERS34(NAME, __VA_ARGS__)
#define NBDL_MEMBERS34(NAME, MNAME, ...) NBDL_MEMBERS2(NAME, MNAME), \
	 NBDL_MEMBERS33(NAME, __VA_ARGS__)
#define NBDL_MEMBERS33(NAME, MNAME, ...) NBDL_MEMBERS2(NAME, MNAME), \
	 NBDL_MEMBERS32(NAME, __VA_ARGS__)
#define NBDL_MEMBERS32(NAME, MNAME, ...) NBDL_MEMBERS2(NAME, MNAME), \
	 NBDL_MEMBERS31(NAME, __VA_ARGS__)
#define NBDL_MEMBERS31(NAME, MNAME, ...) NBDL_MEMBERS2(NAME, MNAME), \
	 NBDL_MEMBERS30(NAME, __VA_ARGS__)
#define NBDL_MEMBERS30(NAME, MNAME, ...) NBDL_MEMBERS2(NAME, MNAME), \
	 NBDL_MEMBERS29(NAME, __VA_ARGS__)
#define NBDL_MEMBERS29(NAME, MNAME, ...) NBDL_MEMBERS2(NAME, MNAME), \
	 NBDL_MEMBERS28(NAME, __VA_ARGS__)
#define NBDL_MEMBERS28(NAME, MNAME, ...) NBDL_MEMBERS2(NAME, MNAME), \
	 NBDL_MEMBERS27(NAME, __VA_ARGS__)
#define NBDL_MEMBERS27(NAME, MNAME, ...) NBDL_MEMBERS2(NAME, MNAME), \
	 NBDL_MEMBERS26(NAME, __VA_ARGS__)
#define NBDL_MEMBERS26(NAME, MNAME, ...) NBDL_MEMBERS2(NAME, MNAME), \
	 NBDL_MEMBERS25(NAME, __VA_ARGS__)
#define NBDL_MEMBERS25(NAME, MNAME, ...) NBDL_MEMBERS2(NAME, MNAME), \
	 NBDL_MEMBERS24(NAME, __VA_ARGS__)
#define NBDL_MEMBERS24(NAME, MNAME, ...) NBDL_MEMBERS2(NAME, MNAME), \
	 NBDL_MEMBERS23(NAME, __VA_ARGS__)
#define NBDL_MEMBERS23(NAME, MNAME, ...) NBDL_MEMBERS2(NAME, MNAME), \
	 NBDL_MEMBERS22(NAME, __VA_ARGS__)
#define NBDL_MEMBERS22(NAME, MNAME, ...) NBDL_MEMBERS2(NAME, MNAME), \
	 NBDL_MEMBERS21(NAME, __VA_ARGS__)
#define NBDL_MEMBERS21(NAME, MNAME, ...) NBDL_MEMBERS2(NAME, MNAME), \
	 NBDL_MEMBERS20(NAME, __VA_ARGS__)
#define NBDL_MEMBERS20(NAME, MNAME, ...) NBDL_MEMBERS2(NAME, MNAME), \
	 NBDL_MEMBERS19(NAME, __VA_ARGS__)
#define NBDL_MEMBERS19(NAME, MNAME, ...) NBDL_MEMBERS2(NAME, MNAME), \
	 NBDL_MEMBERS18(NAME, __VA_ARGS__)
#define NBDL_MEMBERS18(NAME, MNAME, ...) NBDL_MEMBERS2(NAME, MNAME), \
	 NBDL_MEMBERS17(NAME, __VA_ARGS__)
#define NBDL_MEMBERS17(NAME, MNAME, ...) NBDL_MEMBERS2(NAME, MNAME), \
	 NBDL_MEMBERS16(NAME, __VA_ARGS__)
#define NBDL_MEMBERS16(NAME, MNAME, ...) NBDL_MEMBERS2(NAME, MNAME), \
	 NBDL_MEMBERS15(NAME, __VA_ARGS__)
#define NBDL_MEMBERS15(NAME, MNAME, ...) NBDL_MEMBERS2(NAME, MNAME), \
	 NBDL_MEMBERS14(NAME, __VA_ARGS__)
#define NBDL_MEMBERS14(NAME, MNAME, ...) NBDL_MEMBERS2(NAME, MNAME), \
	 NBDL_MEMBERS13(NAME, __VA_ARGS__)
#define NBDL_MEMBERS13(NAME, MNAME, ...) NBDL_MEMBERS2(NAME, MNAME), \
	 NBDL_MEMBERS12(NAME, __VA_ARGS__)
#define NBDL_MEMBERS12(NAME, MNAME, ...) NBDL_MEMBERS2(NAME, MNAME), \
	 NBDL_MEMBERS11(NAME, __VA_ARGS__)
#define NBDL_MEMBERS11(NAME, MNAME, ...) NBDL_MEMBERS2(NAME, MNAME), \
	 NBDL_MEMBERS10(NAME, __VA_ARGS__)
#define NBDL_MEMBERS10(NAME, MNAME, ...) NBDL_MEMBERS2(NAME, MNAME), \
	 NBDL_MEMBERS9(NAME, __VA_ARGS__)
#define NBDL_MEMBERS9(NAME, MNAME, ...) NBDL_MEMBERS2(NAME, MNAME), \
	 NBDL_MEMBERS8(NAME, __VA_ARGS__)
#define NBDL_MEMBERS8(NAME, MNAME, ...) NBDL_MEMBERS2(NAME, MNAME), \
	 NBDL_MEMBERS7(NAME, __VA_ARGS__)
#define NBDL_MEMBERS7(NAME, MNAME, ...) NBDL_MEMBERS2(NAME, MNAME), \
	 NBDL_MEMBERS6(NAME, __VA_ARGS__)
#define NBDL_MEMBERS6(NAME, MNAME, ...) NBDL_MEMBERS2(NAME, MNAME), \
	 NBDL_MEMBERS5(NAME, __VA_ARGS__)
#define NBDL_MEMBERS5(NAME, MNAME, ...) NBDL_MEMBERS2(NAME, MNAME), \
	 NBDL_MEMBERS4(NAME, __VA_ARGS__)
#define NBDL_MEMBERS4(NAME, MNAME, ...) NBDL_MEMBERS2(NAME, MNAME), \
	 NBDL_MEMBERS3(NAME, __VA_ARGS__)
#define NBDL_MEMBERS3(NAME, MNAME, ...) NBDL_MEMBERS2(NAME, MNAME), \
	 NBDL_MEMBERS2(NAME, __VA_ARGS__)

#define NBDL_MEMBERS2(NAME, MNAME) NBDL_MEMBER(&NAME::MNAME)

#endif
