//
// Copyright Jason Rice 2015
// Distributed under the Boost Software License, Version 1.0.
// (See accompanying file LICENSE_1_0.txt or copy at
// http://www.boost.org/LICENSE_1_0.txt)
//
#ifndef _MPDEF_METASTRUCT_SPEC_NAMES

#include<mpdef/MPDEF_VFUNC.hpp>

#define _MPDEF_METASTRUCT_SPEC_NAMES(...) \
  MPDEF_VFUNC(_MPDEF_METASTRUCT_SPEC_NAMES, __VA_ARGS__)

#define _MPDEF_METASTRUCT_SPEC_NAMES63(NAME, ...) \
  NAME, \
  _MPDEF_METASTRUCT_SPEC_NAMES62(__VA_ARGS__)
#define _MPDEF_METASTRUCT_SPEC_NAMES62(NAME, ...) \
  NAME, \
  _MPDEF_METASTRUCT_SPEC_NAMES61(__VA_ARGS__)
#define _MPDEF_METASTRUCT_SPEC_NAMES61(NAME, ...) \
  NAME, \
  _MPDEF_METASTRUCT_SPEC_NAMES60(__VA_ARGS__)
#define _MPDEF_METASTRUCT_SPEC_NAMES60(NAME, ...) \
  NAME, \
  _MPDEF_METASTRUCT_SPEC_NAMES59(__VA_ARGS__)
#define _MPDEF_METASTRUCT_SPEC_NAMES59(NAME, ...) \
  NAME, \
  _MPDEF_METASTRUCT_SPEC_NAMES58(__VA_ARGS__)
#define _MPDEF_METASTRUCT_SPEC_NAMES58(NAME, ...) \
  NAME, \
  _MPDEF_METASTRUCT_SPEC_NAMES57(__VA_ARGS__)
#define _MPDEF_METASTRUCT_SPEC_NAMES57(NAME, ...) \
  NAME, \
  _MPDEF_METASTRUCT_SPEC_NAMES56(__VA_ARGS__)
#define _MPDEF_METASTRUCT_SPEC_NAMES56(NAME, ...) \
  NAME, \
  _MPDEF_METASTRUCT_SPEC_NAMES55(__VA_ARGS__)
#define _MPDEF_METASTRUCT_SPEC_NAMES55(NAME, ...) \
  NAME, \
  _MPDEF_METASTRUCT_SPEC_NAMES54(__VA_ARGS__)
#define _MPDEF_METASTRUCT_SPEC_NAMES54(NAME, ...) \
  NAME, \
  _MPDEF_METASTRUCT_SPEC_NAMES53(__VA_ARGS__)
#define _MPDEF_METASTRUCT_SPEC_NAMES53(NAME, ...) \
  NAME, \
  _MPDEF_METASTRUCT_SPEC_NAMES52(__VA_ARGS__)
#define _MPDEF_METASTRUCT_SPEC_NAMES52(NAME, ...) \
  NAME, \
  _MPDEF_METASTRUCT_SPEC_NAMES51(__VA_ARGS__)
#define _MPDEF_METASTRUCT_SPEC_NAMES51(NAME, ...) \
  NAME, \
  _MPDEF_METASTRUCT_SPEC_NAMES50(__VA_ARGS__)
#define _MPDEF_METASTRUCT_SPEC_NAMES50(NAME, ...) \
  NAME, \
  _MPDEF_METASTRUCT_SPEC_NAMES49(__VA_ARGS__)
#define _MPDEF_METASTRUCT_SPEC_NAMES49(NAME, ...) \
  NAME, \
  _MPDEF_METASTRUCT_SPEC_NAMES48(__VA_ARGS__)
#define _MPDEF_METASTRUCT_SPEC_NAMES48(NAME, ...) \
  NAME, \
  _MPDEF_METASTRUCT_SPEC_NAMES47(__VA_ARGS__)
#define _MPDEF_METASTRUCT_SPEC_NAMES47(NAME, ...) \
  NAME, \
  _MPDEF_METASTRUCT_SPEC_NAMES46(__VA_ARGS__)
#define _MPDEF_METASTRUCT_SPEC_NAMES46(NAME, ...) \
  NAME, \
  _MPDEF_METASTRUCT_SPEC_NAMES45(__VA_ARGS__)
#define _MPDEF_METASTRUCT_SPEC_NAMES45(NAME, ...) \
  NAME, \
  _MPDEF_METASTRUCT_SPEC_NAMES44(__VA_ARGS__)
#define _MPDEF_METASTRUCT_SPEC_NAMES44(NAME, ...) \
  NAME, \
  _MPDEF_METASTRUCT_SPEC_NAMES43(__VA_ARGS__)
#define _MPDEF_METASTRUCT_SPEC_NAMES43(NAME, ...) \
  NAME, \
  _MPDEF_METASTRUCT_SPEC_NAMES42(__VA_ARGS__)
#define _MPDEF_METASTRUCT_SPEC_NAMES42(NAME, ...) \
  NAME, \
  _MPDEF_METASTRUCT_SPEC_NAMES41(__VA_ARGS__)
#define _MPDEF_METASTRUCT_SPEC_NAMES41(NAME, ...) \
  NAME, \
  _MPDEF_METASTRUCT_SPEC_NAMES40(__VA_ARGS__)
#define _MPDEF_METASTRUCT_SPEC_NAMES40(NAME, ...) \
  NAME, \
  _MPDEF_METASTRUCT_SPEC_NAMES39(__VA_ARGS__)
#define _MPDEF_METASTRUCT_SPEC_NAMES39(NAME, ...) \
  NAME, \
  _MPDEF_METASTRUCT_SPEC_NAMES38(__VA_ARGS__)
#define _MPDEF_METASTRUCT_SPEC_NAMES38(NAME, ...) \
  NAME, \
  _MPDEF_METASTRUCT_SPEC_NAMES37(__VA_ARGS__)
#define _MPDEF_METASTRUCT_SPEC_NAMES37(NAME, ...) \
  NAME, \
  _MPDEF_METASTRUCT_SPEC_NAMES36(__VA_ARGS__)
#define _MPDEF_METASTRUCT_SPEC_NAMES36(NAME, ...) \
  NAME, \
  _MPDEF_METASTRUCT_SPEC_NAMES35(__VA_ARGS__)
#define _MPDEF_METASTRUCT_SPEC_NAMES35(NAME, ...) \
  NAME, \
  _MPDEF_METASTRUCT_SPEC_NAMES34(__VA_ARGS__)
#define _MPDEF_METASTRUCT_SPEC_NAMES34(NAME, ...) \
  NAME, \
  _MPDEF_METASTRUCT_SPEC_NAMES33(__VA_ARGS__)
#define _MPDEF_METASTRUCT_SPEC_NAMES33(NAME, ...) \
  NAME, \
  _MPDEF_METASTRUCT_SPEC_NAMES32(__VA_ARGS__)
#define _MPDEF_METASTRUCT_SPEC_NAMES32(NAME, ...) \
  NAME, \
  _MPDEF_METASTRUCT_SPEC_NAMES31(__VA_ARGS__)
#define _MPDEF_METASTRUCT_SPEC_NAMES31(NAME, ...) \
  NAME, \
  _MPDEF_METASTRUCT_SPEC_NAMES30(__VA_ARGS__)
#define _MPDEF_METASTRUCT_SPEC_NAMES30(NAME, ...) \
  NAME, \
  _MPDEF_METASTRUCT_SPEC_NAMES29(__VA_ARGS__)
#define _MPDEF_METASTRUCT_SPEC_NAMES29(NAME, ...) \
  NAME, \
  _MPDEF_METASTRUCT_SPEC_NAMES28(__VA_ARGS__)
#define _MPDEF_METASTRUCT_SPEC_NAMES28(NAME, ...) \
  NAME, \
  _MPDEF_METASTRUCT_SPEC_NAMES27(__VA_ARGS__)
#define _MPDEF_METASTRUCT_SPEC_NAMES27(NAME, ...) \
  NAME, \
  _MPDEF_METASTRUCT_SPEC_NAMES26(__VA_ARGS__)
#define _MPDEF_METASTRUCT_SPEC_NAMES26(NAME, ...) \
  NAME, \
  _MPDEF_METASTRUCT_SPEC_NAMES25(__VA_ARGS__)
#define _MPDEF_METASTRUCT_SPEC_NAMES25(NAME, ...) \
  NAME, \
  _MPDEF_METASTRUCT_SPEC_NAMES24(__VA_ARGS__)
#define _MPDEF_METASTRUCT_SPEC_NAMES24(NAME, ...) \
  NAME, \
  _MPDEF_METASTRUCT_SPEC_NAMES23(__VA_ARGS__)
#define _MPDEF_METASTRUCT_SPEC_NAMES23(NAME, ...) \
  NAME, \
  _MPDEF_METASTRUCT_SPEC_NAMES22(__VA_ARGS__)
#define _MPDEF_METASTRUCT_SPEC_NAMES22(NAME, ...) \
  NAME, \
  _MPDEF_METASTRUCT_SPEC_NAMES21(__VA_ARGS__)
#define _MPDEF_METASTRUCT_SPEC_NAMES21(NAME, ...) \
  NAME, \
  _MPDEF_METASTRUCT_SPEC_NAMES20(__VA_ARGS__)
#define _MPDEF_METASTRUCT_SPEC_NAMES20(NAME, ...) \
  NAME, \
  _MPDEF_METASTRUCT_SPEC_NAMES19(__VA_ARGS__)
#define _MPDEF_METASTRUCT_SPEC_NAMES19(NAME, ...) \
  NAME, \
  _MPDEF_METASTRUCT_SPEC_NAMES18(__VA_ARGS__)
#define _MPDEF_METASTRUCT_SPEC_NAMES18(NAME, ...) \
  NAME, \
  _MPDEF_METASTRUCT_SPEC_NAMES17(__VA_ARGS__)
#define _MPDEF_METASTRUCT_SPEC_NAMES17(NAME, ...) \
  NAME, \
  _MPDEF_METASTRUCT_SPEC_NAMES16(__VA_ARGS__)
#define _MPDEF_METASTRUCT_SPEC_NAMES16(NAME, ...) \
  NAME, \
  _MPDEF_METASTRUCT_SPEC_NAMES15(__VA_ARGS__)
#define _MPDEF_METASTRUCT_SPEC_NAMES15(NAME, ...) \
  NAME, \
  _MPDEF_METASTRUCT_SPEC_NAMES14(__VA_ARGS__)
#define _MPDEF_METASTRUCT_SPEC_NAMES14(NAME, ...) \
  NAME, \
  _MPDEF_METASTRUCT_SPEC_NAMES13(__VA_ARGS__)
#define _MPDEF_METASTRUCT_SPEC_NAMES13(NAME, ...) \
  NAME, \
  _MPDEF_METASTRUCT_SPEC_NAMES12(__VA_ARGS__)
#define _MPDEF_METASTRUCT_SPEC_NAMES12(NAME, ...) \
  NAME, \
  _MPDEF_METASTRUCT_SPEC_NAMES11(__VA_ARGS__)
#define _MPDEF_METASTRUCT_SPEC_NAMES11(NAME, ...) \
  NAME, \
  _MPDEF_METASTRUCT_SPEC_NAMES10(__VA_ARGS__)
#define _MPDEF_METASTRUCT_SPEC_NAMES10(NAME, ...) \
  NAME, \
  _MPDEF_METASTRUCT_SPEC_NAMES9(__VA_ARGS__)
#define _MPDEF_METASTRUCT_SPEC_NAMES9(NAME, ...) \
  NAME, \
  _MPDEF_METASTRUCT_SPEC_NAMES8(__VA_ARGS__)
#define _MPDEF_METASTRUCT_SPEC_NAMES8(NAME, ...) \
  NAME, \
  _MPDEF_METASTRUCT_SPEC_NAMES7(__VA_ARGS__)
#define _MPDEF_METASTRUCT_SPEC_NAMES7(NAME, ...) \
  NAME, \
  _MPDEF_METASTRUCT_SPEC_NAMES6(__VA_ARGS__)
#define _MPDEF_METASTRUCT_SPEC_NAMES6(NAME, ...) \
  NAME, \
  _MPDEF_METASTRUCT_SPEC_NAMES5(__VA_ARGS__)
#define _MPDEF_METASTRUCT_SPEC_NAMES5(NAME, ...) \
  NAME, \
  _MPDEF_METASTRUCT_SPEC_NAMES4(__VA_ARGS__)
#define _MPDEF_METASTRUCT_SPEC_NAMES4(NAME, ...) \
  NAME, \
  _MPDEF_METASTRUCT_SPEC_NAMES3(__VA_ARGS__)
#define _MPDEF_METASTRUCT_SPEC_NAMES3(NAME, ...) \
  NAME, \
  _MPDEF_METASTRUCT_SPEC_NAMES2(__VA_ARGS__)
#define _MPDEF_METASTRUCT_SPEC_NAMES2(NAME, ...) \
  NAME, \
  _MPDEF_METASTRUCT_SPEC_NAMES1(__VA_ARGS__)
#define _MPDEF_METASTRUCT_SPEC_NAMES1(NAME, ...) \
  NAME

#endif
