//
// Copyright Jason Rice 2015
// Distributed under the Boost Software License, Version 1.0.
// (See accompanying file LICENSE_1_0.txt or copy at
// http://www.boost.org/LICENSE_1_0.txt)
//
#ifndef _MPDEF_METASTRUCT_TEMPLATE_PARAMS

#include<mpdef/MPDEF_VFUNC.hpp>

#define _MPDEF_METASTRUCT_TEMPLATE_PARAMS(...) \
  MPDEF_VFUNC(_MPDEF_METASTRUCT_TEMPLATE_PARAMS, __VA_ARGS__)

#define _MPDEF_METASTRUCT_TEMPLATE_PARAMS63(NAME, ...) \
  typename T63, \
  _MPDEF_METASTRUCT_TEMPLATE_PARAMS62(NAME, __VA_ARGS__)
#define _MPDEF_METASTRUCT_TEMPLATE_PARAMS62(NAME, ...) \
  typename T62, \
  _MPDEF_METASTRUCT_TEMPLATE_PARAMS61(NAME, __VA_ARGS__)
#define _MPDEF_METASTRUCT_TEMPLATE_PARAMS61(NAME, ...) \
  typename T61, \
  _MPDEF_METASTRUCT_TEMPLATE_PARAMS60(NAME, __VA_ARGS__)
#define _MPDEF_METASTRUCT_TEMPLATE_PARAMS60(NAME, ...) \
  typename T60, \
  _MPDEF_METASTRUCT_TEMPLATE_PARAMS59(NAME, __VA_ARGS__)
#define _MPDEF_METASTRUCT_TEMPLATE_PARAMS59(NAME, ...) \
  typename T59, \
  _MPDEF_METASTRUCT_TEMPLATE_PARAMS58(NAME, __VA_ARGS__)
#define _MPDEF_METASTRUCT_TEMPLATE_PARAMS58(NAME, ...) \
  typename T58, \
  _MPDEF_METASTRUCT_TEMPLATE_PARAMS57(NAME, __VA_ARGS__)
#define _MPDEF_METASTRUCT_TEMPLATE_PARAMS57(NAME, ...) \
  typename T57, \
  _MPDEF_METASTRUCT_TEMPLATE_PARAMS56(NAME, __VA_ARGS__)
#define _MPDEF_METASTRUCT_TEMPLATE_PARAMS56(NAME, ...) \
  typename T56, \
  _MPDEF_METASTRUCT_TEMPLATE_PARAMS55(NAME, __VA_ARGS__)
#define _MPDEF_METASTRUCT_TEMPLATE_PARAMS55(NAME, ...) \
  typename T55, \
  _MPDEF_METASTRUCT_TEMPLATE_PARAMS54(NAME, __VA_ARGS__)
#define _MPDEF_METASTRUCT_TEMPLATE_PARAMS54(NAME, ...) \
  typename T54, \
  _MPDEF_METASTRUCT_TEMPLATE_PARAMS53(NAME, __VA_ARGS__)
#define _MPDEF_METASTRUCT_TEMPLATE_PARAMS53(NAME, ...) \
  typename T53, \
  _MPDEF_METASTRUCT_TEMPLATE_PARAMS52(NAME, __VA_ARGS__)
#define _MPDEF_METASTRUCT_TEMPLATE_PARAMS52(NAME, ...) \
  typename T52, \
  _MPDEF_METASTRUCT_TEMPLATE_PARAMS51(NAME, __VA_ARGS__)
#define _MPDEF_METASTRUCT_TEMPLATE_PARAMS51(NAME, ...) \
  typename T51, \
  _MPDEF_METASTRUCT_TEMPLATE_PARAMS50(NAME, __VA_ARGS__)
#define _MPDEF_METASTRUCT_TEMPLATE_PARAMS50(NAME, ...) \
  typename T50, \
  _MPDEF_METASTRUCT_TEMPLATE_PARAMS49(NAME, __VA_ARGS__)
#define _MPDEF_METASTRUCT_TEMPLATE_PARAMS49(NAME, ...) \
  typename T49, \
  _MPDEF_METASTRUCT_TEMPLATE_PARAMS48(NAME, __VA_ARGS__)
#define _MPDEF_METASTRUCT_TEMPLATE_PARAMS48(NAME, ...) \
  typename T48, \
  _MPDEF_METASTRUCT_TEMPLATE_PARAMS47(NAME, __VA_ARGS__)
#define _MPDEF_METASTRUCT_TEMPLATE_PARAMS47(NAME, ...) \
  typename T47, \
  _MPDEF_METASTRUCT_TEMPLATE_PARAMS46(NAME, __VA_ARGS__)
#define _MPDEF_METASTRUCT_TEMPLATE_PARAMS46(NAME, ...) \
  typename T46, \
  _MPDEF_METASTRUCT_TEMPLATE_PARAMS45(NAME, __VA_ARGS__)
#define _MPDEF_METASTRUCT_TEMPLATE_PARAMS45(NAME, ...) \
  typename T45, \
  _MPDEF_METASTRUCT_TEMPLATE_PARAMS44(NAME, __VA_ARGS__)
#define _MPDEF_METASTRUCT_TEMPLATE_PARAMS44(NAME, ...) \
  typename T44, \
  _MPDEF_METASTRUCT_TEMPLATE_PARAMS43(NAME, __VA_ARGS__)
#define _MPDEF_METASTRUCT_TEMPLATE_PARAMS43(NAME, ...) \
  typename T43, \
  _MPDEF_METASTRUCT_TEMPLATE_PARAMS42(NAME, __VA_ARGS__)
#define _MPDEF_METASTRUCT_TEMPLATE_PARAMS42(NAME, ...) \
  typename T42, \
  _MPDEF_METASTRUCT_TEMPLATE_PARAMS41(NAME, __VA_ARGS__)
#define _MPDEF_METASTRUCT_TEMPLATE_PARAMS41(NAME, ...) \
  typename T41, \
  _MPDEF_METASTRUCT_TEMPLATE_PARAMS40(NAME, __VA_ARGS__)
#define _MPDEF_METASTRUCT_TEMPLATE_PARAMS40(NAME, ...) \
  typename T40, \
  _MPDEF_METASTRUCT_TEMPLATE_PARAMS39(NAME, __VA_ARGS__)
#define _MPDEF_METASTRUCT_TEMPLATE_PARAMS39(NAME, ...) \
  typename T39, \
  _MPDEF_METASTRUCT_TEMPLATE_PARAMS38(NAME, __VA_ARGS__)
#define _MPDEF_METASTRUCT_TEMPLATE_PARAMS38(NAME, ...) \
  typename T38, \
  _MPDEF_METASTRUCT_TEMPLATE_PARAMS37(NAME, __VA_ARGS__)
#define _MPDEF_METASTRUCT_TEMPLATE_PARAMS37(NAME, ...) \
  typename T37, \
  _MPDEF_METASTRUCT_TEMPLATE_PARAMS36(NAME, __VA_ARGS__)
#define _MPDEF_METASTRUCT_TEMPLATE_PARAMS36(NAME, ...) \
  typename T36, \
  _MPDEF_METASTRUCT_TEMPLATE_PARAMS35(NAME, __VA_ARGS__)
#define _MPDEF_METASTRUCT_TEMPLATE_PARAMS35(NAME, ...) \
  typename T35, \
  _MPDEF_METASTRUCT_TEMPLATE_PARAMS34(NAME, __VA_ARGS__)
#define _MPDEF_METASTRUCT_TEMPLATE_PARAMS34(NAME, ...) \
  typename T34, \
  _MPDEF_METASTRUCT_TEMPLATE_PARAMS33(NAME, __VA_ARGS__)
#define _MPDEF_METASTRUCT_TEMPLATE_PARAMS33(NAME, ...) \
  typename T33, \
  _MPDEF_METASTRUCT_TEMPLATE_PARAMS32(NAME, __VA_ARGS__)
#define _MPDEF_METASTRUCT_TEMPLATE_PARAMS32(NAME, ...) \
  typename T32, \
  _MPDEF_METASTRUCT_TEMPLATE_PARAMS31(NAME, __VA_ARGS__)
#define _MPDEF_METASTRUCT_TEMPLATE_PARAMS31(NAME, ...) \
  typename T31, \
  _MPDEF_METASTRUCT_TEMPLATE_PARAMS30(NAME, __VA_ARGS__)
#define _MPDEF_METASTRUCT_TEMPLATE_PARAMS30(NAME, ...) \
  typename T30, \
  _MPDEF_METASTRUCT_TEMPLATE_PARAMS29(NAME, __VA_ARGS__)
#define _MPDEF_METASTRUCT_TEMPLATE_PARAMS29(NAME, ...) \
  typename T29, \
  _MPDEF_METASTRUCT_TEMPLATE_PARAMS28(NAME, __VA_ARGS__)
#define _MPDEF_METASTRUCT_TEMPLATE_PARAMS28(NAME, ...) \
  typename T28, \
  _MPDEF_METASTRUCT_TEMPLATE_PARAMS27(NAME, __VA_ARGS__)
#define _MPDEF_METASTRUCT_TEMPLATE_PARAMS27(NAME, ...) \
  typename T27, \
  _MPDEF_METASTRUCT_TEMPLATE_PARAMS26(NAME, __VA_ARGS__)
#define _MPDEF_METASTRUCT_TEMPLATE_PARAMS26(NAME, ...) \
  typename T26, \
  _MPDEF_METASTRUCT_TEMPLATE_PARAMS25(NAME, __VA_ARGS__)
#define _MPDEF_METASTRUCT_TEMPLATE_PARAMS25(NAME, ...) \
  typename T25, \
  _MPDEF_METASTRUCT_TEMPLATE_PARAMS24(NAME, __VA_ARGS__)
#define _MPDEF_METASTRUCT_TEMPLATE_PARAMS24(NAME, ...) \
  typename T24, \
  _MPDEF_METASTRUCT_TEMPLATE_PARAMS23(NAME, __VA_ARGS__)
#define _MPDEF_METASTRUCT_TEMPLATE_PARAMS23(NAME, ...) \
  typename T23, \
  _MPDEF_METASTRUCT_TEMPLATE_PARAMS22(NAME, __VA_ARGS__)
#define _MPDEF_METASTRUCT_TEMPLATE_PARAMS22(NAME, ...) \
  typename T22, \
  _MPDEF_METASTRUCT_TEMPLATE_PARAMS21(NAME, __VA_ARGS__)
#define _MPDEF_METASTRUCT_TEMPLATE_PARAMS21(NAME, ...) \
  typename T21, \
  _MPDEF_METASTRUCT_TEMPLATE_PARAMS20(NAME, __VA_ARGS__)
#define _MPDEF_METASTRUCT_TEMPLATE_PARAMS20(NAME, ...) \
  typename T20, \
  _MPDEF_METASTRUCT_TEMPLATE_PARAMS19(NAME, __VA_ARGS__)
#define _MPDEF_METASTRUCT_TEMPLATE_PARAMS19(NAME, ...) \
  typename T19, \
  _MPDEF_METASTRUCT_TEMPLATE_PARAMS18(NAME, __VA_ARGS__)
#define _MPDEF_METASTRUCT_TEMPLATE_PARAMS18(NAME, ...) \
  typename T18, \
  _MPDEF_METASTRUCT_TEMPLATE_PARAMS17(NAME, __VA_ARGS__)
#define _MPDEF_METASTRUCT_TEMPLATE_PARAMS17(NAME, ...) \
  typename T17, \
  _MPDEF_METASTRUCT_TEMPLATE_PARAMS16(NAME, __VA_ARGS__)
#define _MPDEF_METASTRUCT_TEMPLATE_PARAMS16(NAME, ...) \
  typename T16, \
  _MPDEF_METASTRUCT_TEMPLATE_PARAMS15(NAME, __VA_ARGS__)
#define _MPDEF_METASTRUCT_TEMPLATE_PARAMS15(NAME, ...) \
  typename T15, \
  _MPDEF_METASTRUCT_TEMPLATE_PARAMS14(NAME, __VA_ARGS__)
#define _MPDEF_METASTRUCT_TEMPLATE_PARAMS14(NAME, ...) \
  typename T14, \
  _MPDEF_METASTRUCT_TEMPLATE_PARAMS13(NAME, __VA_ARGS__)
#define _MPDEF_METASTRUCT_TEMPLATE_PARAMS13(NAME, ...) \
  typename T13, \
  _MPDEF_METASTRUCT_TEMPLATE_PARAMS12(NAME, __VA_ARGS__)
#define _MPDEF_METASTRUCT_TEMPLATE_PARAMS12(NAME, ...) \
  typename T12, \
  _MPDEF_METASTRUCT_TEMPLATE_PARAMS11(NAME, __VA_ARGS__)
#define _MPDEF_METASTRUCT_TEMPLATE_PARAMS11(NAME, ...) \
  typename T11, \
  _MPDEF_METASTRUCT_TEMPLATE_PARAMS10(NAME, __VA_ARGS__)
#define _MPDEF_METASTRUCT_TEMPLATE_PARAMS10(NAME, ...) \
  typename T10, \
  _MPDEF_METASTRUCT_TEMPLATE_PARAMS9(NAME, __VA_ARGS__)
#define _MPDEF_METASTRUCT_TEMPLATE_PARAMS9(NAME, ...) \
  typename T9, \
  _MPDEF_METASTRUCT_TEMPLATE_PARAMS8(NAME, __VA_ARGS__)
#define _MPDEF_METASTRUCT_TEMPLATE_PARAMS8(NAME, ...) \
  typename T8, \
  _MPDEF_METASTRUCT_TEMPLATE_PARAMS7(NAME, __VA_ARGS__)
#define _MPDEF_METASTRUCT_TEMPLATE_PARAMS7(NAME, ...) \
  typename T7, \
  _MPDEF_METASTRUCT_TEMPLATE_PARAMS6(NAME, __VA_ARGS__)
#define _MPDEF_METASTRUCT_TEMPLATE_PARAMS6(NAME, ...) \
  typename T6, \
  _MPDEF_METASTRUCT_TEMPLATE_PARAMS5(NAME, __VA_ARGS__)
#define _MPDEF_METASTRUCT_TEMPLATE_PARAMS5(NAME, ...) \
  typename T5, \
  _MPDEF_METASTRUCT_TEMPLATE_PARAMS4(NAME, __VA_ARGS__)
#define _MPDEF_METASTRUCT_TEMPLATE_PARAMS4(NAME, ...) \
  typename T4, \
  _MPDEF_METASTRUCT_TEMPLATE_PARAMS3(NAME, __VA_ARGS__)
#define _MPDEF_METASTRUCT_TEMPLATE_PARAMS3(NAME, ...) \
  typename T3, \
  _MPDEF_METASTRUCT_TEMPLATE_PARAMS2(NAME, __VA_ARGS__)
#define _MPDEF_METASTRUCT_TEMPLATE_PARAMS2(NAME, ...) \
  typename T2, \
  _MPDEF_METASTRUCT_TEMPLATE_PARAMS1(NAME, __VA_ARGS__)
#define _MPDEF_METASTRUCT_TEMPLATE_PARAMS1(NAME, ...) \
  typename T1

#endif
