//
// Copyright Jason Rice 2025
// Distributed under the Boost Software License, Version 1.0.
// (See accompanying file LICENSE_1_0.txt or copy at
// http://www.boost.org/LICENSE_1_0.txt)
//
#ifndef NBDL_SPEC_HPP
#define NBDL_SPEC_HPP

// FIXME nbdl::assign probably does not need its own file.
#include <nbdl/assign.hpp>
#include <nbdl/concept/extras.hpp>
#include <nbdl/match.hpp>
#include <nbdl/strong_alias.hpp>
#include <nbdl/tags.hpp>
#include <nbdl/variant.hpp>
#include <nbdl/variant_holder.hpp>
#include <boost/hana/functional/overload.hpp>
#include <concepts>
#include <type_traits>
#include <utility>

// Include and define functions and hooks
// required for code generated by the
// (nbdl spec) Scheme DSL.

namespace nbdl {
  // Implement a conditional check that maps
  // to bool that is false only when the object
  // is convertible to bool evaluating to false.
  template <std::convertible_to<bool> T>
  constexpr bool scheme_like_cond(T const& value) {
    return static_cast<bool>(input);
  }

  constexpr bool scheme_like_cond(auto const& value) {
    return true;
  }
}

#endif
